services:
  backend:
    build:
      context: ./backend
    container_name: tts-backend
    ports:
      - "8000:8000"
    environment:
      COQUI_TTS_MODEL: "tts_models/multilingual/multi-dataset/xtts_v2"
      XTTS_CONFIG_PATH: "/app/volumes/voices/xtts/config.json"
      XTTS_CHECKPOINT_DIR: "/app/volumes/voices/xtts/"
      USE_DEEPSPEED: "false"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    volumes:
      - ./volumes:/app/volumes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
    container_name: tts-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE: "http://localhost:8000"
    depends_on:
      - backend
