services:
  backend:
    build:
      context: ./backend
      args:
        PRELOAD_MODEL: "tts_models/en/ljspeech/vits"
    container_name: tts-backend
    ports:
      - "8000:8000"
    environment:

      COQUI_TTS_MODEL: "tts_models/en/ljspeech/vits"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    volumes:
      - ./volumes:/app/volumes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
    container_name: tts-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: "http://localhost:8000"
    depends_on:
      - backend
